eureka:
  client:
    service-url:
      defaultZone: http://localhost:8762/eureka

spring:
  messages:
    encoding: UTF-8
    fallback-to-system-locale: true
  web:
    locale-resolver: accept_header
